# This is a basic workflow to help you get started with Actions

name: Hello in CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: step1
        uses: actions/hello-world-javascript-action@main
        with:
         who-to-greet: 'Mona the Octocat'
